In [ ]:
import numpy as np

print("NumPy version:", np.__version__)


NumPy version: 2.0.2


In [ ]:
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("2D Array:")
print(arr_2d)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("3D Array:")
print(arr_3d)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print("Dimensions:", arr_2d.ndim)
print("Shape:", arr_2d.shape)
print("Total elements:", arr_2d.size)
print("Data type:", arr_2d.dtype)

Dimensions: 2
Shape: (3, 3)
Total elements: 9
Data type: int64


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])
print("Third element:", arr[2])
print("Last element:", arr[-1])

First element: 10
Third element: 30
Last element: 50


In [ ]:
arr_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Element at row 1, column 2:", arr_2d[1, 2])

Element at row 1, column 2: 60


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("First three elements:", arr[:3])
print("Elements from index 2:", arr[2:])
print("Elements from index 1 to 3:", arr[1:4])

First three elements: [10 20 30]
Elements from index 2: [30 40 50]
Elements from index 1 to 3: [20 30 40]


In [ ]:
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr_2d[0:2, 1:3])

[[2 3]
 [5 6]]


In [ ]:
arr = np.arange(1, 13)

print("Original array:")
print(arr)

reshaped = arr.reshape(3, 4)

print("\nReshaped array:")
print(reshaped)

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
zeros_array = np.zeros((3, 4))

print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones_array = np.ones((2, 3))

print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr = np.arange(1, 11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.linspace(0, 10, 5)

print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]


In [ ]:
numbers = np.array([1, 2, 3, 4, 5])

result = numbers * 10

print(result)

[10 20 30 40 50]


In [ ]:
numbers = np.array([10, 25, 30, 45, 50, 65])

mask = numbers > 30

print(mask)
print(numbers[mask])

[False False False  True  True  True]
[45 50 65]


In [ ]:
numbers = np.array([10, 20, 30, 40])

result = numbers + 5

print(result)

[15 25 35 45]


In [ ]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

result = matrix + 10

print(result)

[[20 30 40]
 [50 60 70]]


In [ ]:
data = np.array([10, 20, 30, 40, 50])

In [ ]:
print("Sum:", np.sum(data))

Sum: 150


In [ ]:
print("Mean:", np.mean(data))

Mean: 30.0


In [ ]:
print("Minimum:", np.min(data))

Minimum: 10


In [ ]:
print("Maximum:", np.max(data))

Maximum: 50


In [ ]:
print("Median:", np.median(data))

Median: 30.0


In [ ]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Median:", np.median(data))

Sum: 450
Mean: 50.0
Minimum: 10
Maximum: 90
Median: 50.0


In [ ]:
print("Column-wise sum:")
print(np.sum(data, axis=0))

print("Row-wise sum:")
print(np.sum(data, axis=1))

Column-wise sum:
[120 150 180]
Row-wise sum:
[ 60 150 240]
